#!/usr/bin/env bash
set -euo pipefail

config_file="$HOME/.config/TWM/i3/local.conf"

if ! command -v xrandr >/dev/null 2>&1; then
  echo "xrandr not found."
  exit 1
fi

outputs=()
while IFS= read -r line; do
  name="$(printf '%s' "$line" | awk '{print $1}')"
  outputs+=("$name")
done < <(xrandr --query | awk '/ connected/ {print}')

if [ "${#outputs[@]}" -eq 0 ]; then
  echo "No connected outputs detected."
  exit 1
fi

echo "Select output:"
for i in "${!outputs[@]}"; do
  printf '%d) %s\n' "$((i + 1))" "${outputs[$i]}"
done

read -r -p "Enter number: " choice
if ! [[ "$choice" =~ ^[0-9]+$ ]] || [ "$choice" -lt 1 ] || [ "$choice" -gt "${#outputs[@]}" ]; then
  echo "Invalid choice."
  exit 1
fi

output="${outputs[$((choice - 1))]}"

read -r -p "Scale (e.g. 1.0, 0.75): " scale
if [ -z "$scale" ]; then
  echo "Scale is required."
  exit 1
fi

mkdir -p "$(dirname "$config_file")"
cat >"$config_file" <<EOF
# Auto-generated by setup-xrandr-scale.sh
exec_always --no-startup-id xrandr --output $output --scale ${scale}x${scale}
EOF

echo "Wrote $config_file"
echo "Reload i3 to apply: i3-msg reload"
read -r -p "Exit i3 to restart now? (y/N): " exit_choice
if [ "$exit_choice" = "y" ] || [ "$exit_choice" = "Y" ]; then
  i3-msg exit
fi
